# Generated by Django 4.2.18 on 2025-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField(verbose_name='Номер стола')),
                ('total_price', models.PositiveIntegerField(verbose_name='Итоговая цена')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
                ('items', models.ManyToManyField(to='orders.dishes', verbose_name='Блюда')),
            ],
        ),
    ]
