# Generated by Django 4.2.18 on 2025-01-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_dishes_options_alter_orders_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('ready', 'Готов'), ('paid', 'Оплачено')], default='waiting', max_length=10, verbose_name='Статус'),
        ),
    ]
